### ISSUE TITLE
Never implement

### ISSUE THREAD

**Issue by aadamsx** [AdamBrodzinski/pipes-js#1]
did you ever get a chance to implement this?

**Comment by AdamBrodzinski** [comment]
Not fully... I started to and stopped when babel allowed me to hook into their transpiler but ran out of time and energy. However you can still use something similar which is on my elixir-stdlib-js library:

```javascript
_.mixin({
  // mixin IO.inspect for convenience
  inspect(arg1) {
    console.log(arg1);
    return arg1;
  },

  // similar to `thru` but this allows users to
  // use function with more than one argument
  // example:
  //   pipe("555 222-000)
  //   .run(stripChars, "-")
  //   .run(IO.inspect)
  //   .run(stripChars, " ")
  //   .value()
  //
  run(firstParam, func, ...restParams) {
    return func(firstParam, ...restParams);
  },
});
```
https://github.com/AdamBrodzinski/elixir-stdlib-js/blob/master/src/index.js#L29

It's using a mixin with underscore to allow you to use `.run` with a lodash/underscore chain instead of `|>`.

**Comment by AdamBrodzinski** [comment]
Happy to accept a PR though ;)

**Comment by allanbreyes** [comment]
It's been a while, but I was searching for this precise functionality. Looks like it's part of the TC39 proposal: https://github.com/tc39/proposal-pipeline-operator

**Comment by AdamBrodzinski** [comment]
Yeah! Glad that it made it into core 😄
